import { useState, type FormEvent } from 'react';
import { Check, Send } from 'lucide-react';

const benefits = ['Custom-printed ribbon and belly bands with your logo', 'Dispatch to multiple addresses from one order', 'GST invoicing and flexible payment options', 'A sample hamper before confirming the full run'];

export default function Corporate() {
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent) { event.preventDefault(); setSent(true); }
  return <section className="py-2 sm:py-6"><div className="grid gap-10 lg:grid-cols-2 lg:gap-14"><div><img src="https://images.pexels.com/photos/6690454/pexels-photo-6690454.jpeg?auto=compress&cs=tinysrgb&h=900&w=900" alt="Corporate gift hamper" className="aspect-square w-full rounded-3xl object-cover" /><ul className="mt-8 space-y-4">{benefits.map((benefit) => <li key={benefit} className="flex gap-3 text-sm text-ink-700/70 dark:text-gray-300"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-gold-500/15 text-gold-600"><Check className="h-3.5 w-3.5" /></span>{benefit}</li>)}</ul></div><form onSubmit={submit} className="h-fit rounded-3xl bg-cream-50 p-6 ring-1 ring-cream-200 sm:p-8 dark:bg-gray-800 dark:ring-gray-700"><p className="text-xs font-medium uppercase tracking-[0.2em] text-gold-600">Request a quote</p><h2 className="mt-3 font-display text-3xl font-semibold text-wine-700 dark:text-white">Let’s make it memorable</h2><p className="mt-2 text-sm text-ink-700/65 dark:text-gray-300">Tell us a little about your gifting requirement and we’ll get back to you.</p><div className="mt-7 space-y-4"><Field label="Company"><input required className="input" placeholder="Your company name" /></Field><Field label="Work email"><input required type="email" className="input" placeholder="you@company.com" /></Field><Field label="Approximate quantity"><input required min="25" type="number" className="input" placeholder="60" /></Field><Field label="Occasion and budget"><textarea required rows={5} className="input resize-none" placeholder="For example: Diwali hampers for 80 employees, budget ₹2,000 per gift." /></Field></div>{sent && <p className="mt-4 rounded-xl bg-sage-500/15 px-4 py-3 text-sm text-sage-500">Thank you — your quote request has been received.</p>}<button className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full bg-gold-500 px-5 py-3.5 text-sm font-semibold text-ink-900 transition-colors hover:bg-gold-400" type="submit"><Send className="h-4 w-4" />Request a quote</button></form></div></section>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-medium uppercase tracking-wide text-ink-700/60 dark:text-gray-400">{label}</span>{children}</label>; }
